name: steps examples
on:
  push
jobs:
  marketplace:
    runs-on: ubuntu-latest
    steps:
      - name: Example of use of marketplace
        uses: actions/setup-node@v2
        with:
          node-version: '12'
      - name: shows node version configured.
        run: node --version
